#!/usr/bin/env bash
# This script was generated by bashly 1.3.6 (https://bashly.dev)
# Modifying it manually is not recommended

# :wrapper.bash3_bouncer
if ((BASH_VERSINFO[0] < 4 || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 2))); then
  printf "bash version 4.2 or higher is required\n" >&2
  exit 1
fi

# :command.master_script

# :command.version_command
version_command() {
  echo "$version"
}

# :command.usage
mantis_mcp_usage() {
  printf "mantis-mcp - Setup and manage the MantisBT MCP server\n\n"

  printf "%s\n" "Usage:"
  printf "  mantis-mcp COMMAND\n"
  printf "  mantis-mcp [COMMAND] --help | -h\n"
  printf "  mantis-mcp --version | -v\n"
  echo
  # :command.usage_commands
  printf "%s\n" "Commands:"
  printf "  %s   Configure mantis-mcp for Claude Desktop and/or Claude Code\n" "setup"
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    # :command.usage_options
    printf "%s\n" "Options:"

    # :command.usage_fixed_flags
    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo
    printf "  %s\n" "--version, -v"
    printf "    Show version number\n"
    echo

  fi
}

# :command.usage
mantis_mcp_setup_usage() {
  printf "mantis-mcp setup - Configure mantis-mcp for Claude Desktop and/or Claude Code\n\n"

  printf "%s\n" "Usage:"
  printf "  mantis-mcp setup [OPTIONS]\n"
  printf "  mantis-mcp setup --help | -h\n"
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    # :command.usage_options
    printf "%s\n" "Options:"

    # :command.usage_flags
    # :flag.usage
    printf "  %s\n" "--api-url, -u URL"
    printf "    MantisBT REST API URL (e.g. https://debug.espero.it/mantis/api/rest)\n"
    echo

    # :flag.usage
    printf "  %s\n" "--api-key, -k KEY"
    printf "    MantisBT API token\n"
    echo

    # :flag.usage
    printf "  %s\n" "--target, -t TARGET"
    printf "    Target to configure: desktop, cli, or both\n"
    printf "    %s\n" "Allowed: desktop, cli, both"
    printf "    %s\n" "Default: both"
    echo

    # :command.usage_fixed_flags
    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo

  fi
}

# :command.normalize_input
# :command.normalize_input_function
normalize_input() {
  local arg passthru flags
  passthru=false

  while [[ $# -gt 0 ]]; do
    arg="$1"
    if [[ $passthru == true ]]; then
      input+=("$arg")
    elif [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
      input+=("${BASH_REMATCH[1]}")
      input+=("${BASH_REMATCH[2]}")
    elif [[ $arg =~ ^(-[a-zA-Z0-9])=(.+)$ ]]; then
      input+=("${BASH_REMATCH[1]}")
      input+=("${BASH_REMATCH[2]}")
    elif [[ $arg =~ ^-([a-zA-Z0-9][a-zA-Z0-9]+)$ ]]; then
      flags="${BASH_REMATCH[1]}"
      for ((i = 0; i < ${#flags}; i++)); do
        input+=("-${flags:i:1}")
      done
    elif [[ "$arg" == "--" ]]; then
      passthru=true
      input+=("$arg")
    else
      input+=("$arg")
    fi

    shift
  done
}

# :command.inspect_args
inspect_args() {
  local k

  if ((${#args[@]})); then
    readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
    echo args:
    for k in "${sorted_keys[@]}"; do
      echo "- \${args[$k]} = ${args[$k]}"
    done
  else
    echo args: none
  fi

  if ((${#deps[@]})); then
    readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
    echo
    echo deps:
    for k in "${sorted_keys[@]}"; do
      echo "- \${deps[$k]} = ${deps[$k]}"
    done
  fi

  if ((${#env_var_names[@]})); then
    readarray -t sorted_names < <(printf '%s\n' "${env_var_names[@]}" | sort)
    echo
    echo "environment variables:"
    for k in "${sorted_names[@]}"; do
      echo "- \$$k = ${!k:-}"
    done
  fi
}

# :command.command_functions
# :command.function
mantis_mcp_setup_command() {

  # src/setup_command.sh
  detect_platform() {
    if [[ -n "${WSL_DISTRO_NAME:-}" ]] || grep -qi microsoft /proc/version 2>/dev/null; then
      echo "wsl"
    elif [[ "$OSTYPE" == "darwin"* ]]; then
      echo "macos"
    elif [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]] || [[ -n "${WINDIR:-}" ]]; then
      echo "windows"
    else
      echo "linux"
    fi
  }

  PLATFORM=$(detect_platform)
  echo "Detected platform: $PLATFORM"
  echo ""

  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  PROJECT_DIR="$SCRIPT_DIR"
  INDEX_PATH="$PROJECT_DIR/dist/index.js"

  if [[ ! -f "$INDEX_PATH" ]]; then
    echo "Error: dist/index.js not found at $INDEX_PATH"
    echo "Please run 'npm run build' first."
    exit 1
  fi

  API_URL="${args[--api-url]:-}"
  if [[ -z "$API_URL" ]]; then
    echo "Enter your MantisBT REST API URL"
    echo "(e.g. https://debug.espero.it/mantis/api/rest)"
    read -rp "> " API_URL
    echo ""
  fi

  if [[ ! "$API_URL" =~ ^https?:// ]]; then
    echo "Error: Invalid URL. Must start with http:// or https://"
    exit 1
  fi

  API_KEY="${args[--api-key]:-}"
  if [[ -z "$API_KEY" ]]; then
    echo "Enter your MantisBT API token"
    echo "(from MantisBT → My Account → API Tokens)"
    read -rp "> " API_KEY
    echo ""
  fi

  if [[ -z "$API_KEY" ]]; then
    echo "Error: API token cannot be empty."
    exit 1
  fi

  echo "Testing API connection..."
  HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: $API_KEY" "$API_URL/projects" 2>/dev/null)
  if [[ "$HTTP_CODE" == "200" ]]; then
    echo "Connection successful!"
    echo ""
  elif [[ "$HTTP_CODE" == "401" ]]; then
    echo "Warning: Got 401 Unauthorized. The token may be invalid or the server needs the Authorization header fix."
    echo "Continuing anyway..."
    echo ""
  else
    echo "Warning: Got HTTP $HTTP_CODE. The URL may be incorrect."
    echo "Continuing anyway..."
    echo ""
  fi

  TARGET="${args[--target]}"

  build_mcp_json() {
    local cmd="$1"
    local args_json="$2"

    cat <<MCPEOF
{
  "mcpServers": {
    "mantis": {
      "command": "$cmd",
      "args": $args_json,
      "env": {
        "MANTIS_API_URL": "$API_URL",
        "MANTIS_API_KEY": "$API_KEY"
      }
    }
  }
}
MCPEOF
  }

  get_desktop_cmd() {
    if [[ "$PLATFORM" == "wsl" ]]; then
      echo "wsl"
    else
      echo "node"
    fi
  }

  get_desktop_args_json() {
    if [[ "$PLATFORM" == "wsl" ]]; then
      echo "[\"bash\", \"-c\", \"cd $PROJECT_DIR && node dist/index.js\"]"
    elif [[ "$PLATFORM" == "windows" ]]; then
      local win_path
      win_path=$(cygpath -w "$INDEX_PATH" 2>/dev/null || echo "$INDEX_PATH")
      win_path="${win_path//\\/\\\\}"
      echo "[\"$win_path\"]"
    else
      echo "[\"$INDEX_PATH\"]"
    fi
  }

  get_cli_cmd() {
    echo "node"
  }

  get_cli_args_json() {
    echo "[\"$INDEX_PATH\"]"
  }

  get_desktop_config_path() {
    case "$PLATFORM" in
      wsl)
        # Windows path from WSL
        local win_appdata
        win_appdata=$(cmd.exe /C "echo %APPDATA%" 2>/dev/null | tr -d '\r')
        if [[ -n "$win_appdata" ]]; then
          local wsl_path
          wsl_path=$(wslpath "$win_appdata" 2>/dev/null)
          echo "$wsl_path/Claude/claude_desktop_config.json"
        else
          echo ""
        fi
        ;;
      macos)
        echo "$HOME/Library/Application Support/Claude/claude_desktop_config.json"
        ;;
      windows)
        echo "$APPDATA/Claude/claude_desktop_config.json"
        ;;
      linux)
        echo "$HOME/.config/claude/claude_desktop_config.json"
        ;;
    esac
  }

  merge_mcp_config() {
    local config_file="$1"
    local mcp_json="$2"

    if [[ ! -f "$config_file" ]]; then
      # Create directory if needed
      mkdir -p "$(dirname "$config_file")"
      echo "$mcp_json" > "$config_file"
      return
    fi

    # Use node to merge JSON (handles existing mcpServers)
    node -e "
      const fs = require('fs');
      const existing = JSON.parse(fs.readFileSync('$config_file', 'utf8'));
      const newConfig = JSON.parse(\`$mcp_json\`);
      existing.mcpServers = existing.mcpServers || {};
      Object.assign(existing.mcpServers, newConfig.mcpServers);
      fs.writeFileSync('$config_file', JSON.stringify(existing, null, 2) + '\n');
    " 2>/dev/null

    if [[ $? -ne 0 ]]; then
      echo "Warning: Could not merge into existing config. Writing new file."
      echo "$mcp_json" > "$config_file"
    fi
  }

  if [[ "$TARGET" == "desktop" ]] || [[ "$TARGET" == "both" ]]; then
    echo "=== Configuring Claude Desktop ==="

    DESKTOP_CONFIG_PATH=$(get_desktop_config_path)

    if [[ -z "$DESKTOP_CONFIG_PATH" ]]; then
      echo "Could not determine Claude Desktop config path for this platform."
      echo "Please manually add the MCP config to your claude_desktop_config.json"
    else
      MCP_JSON=$(build_mcp_json "$(get_desktop_cmd)" "$(get_desktop_args_json)")

      merge_mcp_config "$DESKTOP_CONFIG_PATH" "$MCP_JSON"
      echo "Written to: $DESKTOP_CONFIG_PATH"
      echo "Please restart Claude Desktop to apply changes."
    fi
    echo ""
  fi

  if [[ "$TARGET" == "cli" ]] || [[ "$TARGET" == "both" ]]; then
    echo "=== Configuring Claude Code (CLI) ==="

    MCP_JSON_FILE="$PROJECT_DIR/.mcp.json"
    MCP_JSON=$(build_mcp_json "$(get_cli_cmd)" "$(get_cli_args_json)")

    echo "$MCP_JSON" > "$MCP_JSON_FILE"
    echo "Written to: $MCP_JSON_FILE"
    echo "Claude Code will prompt you to approve the MCP server on first use."
    echo ""
  fi

  ENV_FILE="$PROJECT_DIR/.env"
  if [[ ! -f "$ENV_FILE" ]]; then
    cat > "$ENV_FILE" <<ENVEOF
MANTIS_API_URL=$API_URL
MANTIS_API_KEY=$API_KEY
DB_PATH=./mantis-mcp.db
EMBEDDING_MODEL=Xenova/paraphrase-multilingual-MiniLM-L12-v2
SYNC_BATCH_SIZE=50
SYNC_ON_STARTUP=false
LOG_LEVEL=info
ENVEOF
    echo "Created .env file at: $ENV_FILE"
  else
    echo ".env file already exists at: $ENV_FILE (not overwritten)"
  fi

  echo ""
  echo "Setup complete! Next steps:"
  echo "  1. Restart Claude Desktop (if configured)"
  echo "  2. Ask Claude to 'sync the MantisBT index' to enable semantic search"
  echo "  3. Then search with natural language queries!"

}

# :command.parse_requirements
parse_requirements() {
  local key

  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --version | -v)
        version_command
        exit
        ;;

      --help | -h)
        long_usage=yes
        mantis_mcp_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.command_filter
  action=${1:-}

  case $action in
    -*) ;;

    setup)
      action="setup"
      shift
      mantis_mcp_setup_parse_requirements "$@"
      shift $#
      ;;

    # :command.command_fallback
    "")
      mantis_mcp_usage >&2
      exit 1
      ;;

    *)
      printf "invalid command: %s\n" "$action" >&2
      exit 1
      ;;

  esac

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_simple
        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

}

# :command.parse_requirements
mantis_mcp_setup_parse_requirements() {
  local key

  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        mantis_mcp_setup_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.command_filter
  action="setup"

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      # :flag.case
      --api-url | -u)

        # :flag.case_arg
        if [[ -n ${2+x} ]]; then
          args['--api-url']="$2"
          shift
          shift
        else
          printf "%s\n" "--api-url requires an argument: --api-url, -u URL" >&2
          exit 1
        fi
        ;;

      # :flag.case
      --api-key | -k)

        # :flag.case_arg
        if [[ -n ${2+x} ]]; then
          args['--api-key']="$2"
          shift
          shift
        else
          printf "%s\n" "--api-key requires an argument: --api-key, -k KEY" >&2
          exit 1
        fi
        ;;

      # :flag.case
      --target | -t)

        # :flag.case_arg
        if [[ -n ${2+x} ]]; then
          args['--target']="$2"
          shift
          shift
        else
          printf "%s\n" "--target requires an argument: --target, -t TARGET" >&2
          exit 1
        fi
        ;;

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_simple
        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

  # :command.default_assignments
  [[ -n ${args['--target']:-} ]] || args['--target']="both"

  # :command.whitelist_filter
  if [[ ${args['--target']:-} ]] && [[ ! ${args['--target']:-} =~ ^(desktop|cli|both)$ ]]; then
    printf "%s\n" "--target must be one of: desktop, cli, both" >&2
    exit 1
  fi

}

# :command.initialize
initialize() {
  declare -g version="1.0.0"
  set -e

}

# :command.run
run() {
  # :command.globals
  declare -g long_usage=''
  declare -g -A args=()
  declare -g -A deps=()
  declare -g -a env_var_names=()
  declare -g -a input=()

  normalize_input "$@"
  parse_requirements "${input[@]}"

  case "$action" in
    "setup") mantis_mcp_setup_command ;;
  esac
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  # :command.start
  command_line_args=("$@")
  initialize
  run "${command_line_args[@]}"
fi
